FROM ubuntu:22.04

# Run the command to install the required packages
RUN apt-get update && apt-get install -y iputils-ping && apt-get install -y iproute2 && apt-get install -y frr coreutils
RUN echo "!/etc/frr/frr.conf" > /etc/frr/frr.conf && echo "frr version 7.5" >> /etc/frr/frr.conf && \
    echo "frr defaults traditional" >> /etc/frr/frr.conf && echo "frr defaults traditional" >> /etc/frr/frr.conf && \
    echo "router ospf" >> /etc/frr/frr.conf && echo "  redistribute connected" >> /etc/frr/frr.conf && \
    echo "log syslog informational" >> log syslog informational


# Execute apache in foreground as default
CMD ["/bin/bash"]