FROM ubuntu:22.04

# Run the command to install the required packages
RUN apt-get update && apt-get install -y iputils-ping && apt-get install -y iproute2 coreutils iptables nodejs npm syslog-ng
   


CMD ["/bin/bash"]




