FROM ubuntu:22.04

# Run the command to install the required packages. This command adds a layer to the image.
RUN apt-get update && apt-get install -y iputils-ping && apt-get install -y iproute2 iptables
#the packet installed are the one util to add a route or ping a node.

COPY entrypoints/ep_red1.sh entrypoints/ep_red1.sh
COPY entrypoints/ep_red2.sh entrypoints/ep_red2.sh
COPY entrypoints/ep_red3.sh entrypoints/ep_red3.sh
COPY entrypoints/ep_red4.sh entrypoints/ep_red4.sh




#make the scripts executable 
RUN chmod +x /entrypoints/ep_red1.sh /entrypoints/ep_red2.sh /entrypoints/ep_red3.sh /entrypoints/ep_red4.sh



CMD ["/bin/bash"]