FROM ubuntu:22.04

# Run the command to install the required packages
RUN apt-get update && apt-get install -y iputils-ping && apt-get install -y iproute2 coreutils iptables nodejs npm syslog-ng
   
#add the entryscripts to the common image of the router

COPY entrypoints/ep_servidor.sh entrypoints/ep_servidor.sh

RUN chmod +x /entrypoints/ep_servidor.sh
CMD ["/bin/bash"]




